/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/action-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an action item */
        delete: operations["delete_action_item"];
        options?: never;
        head?: never;
        /** Update an action item */
        patch: operations["update_action_item"];
        trace?: never;
    };
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List channels */
        get: operations["list_channels"];
        put?: never;
        /** Create a channel */
        post: operations["create_channel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a channel (its meetings stay, unassigned) */
        delete: operations["delete_channel"];
        options?: never;
        head?: never;
        /** Rename a channel */
        patch: operations["rename_channel"];
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meetings */
        get: operations["list_meetings"];
        put?: never;
        /**
         * Create a meeting
         * @description With `segments`, the transcript is summarised by the AI and the request counts towards the AI rate limit; without them it does not.
         */
        post: operations["create_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a meeting */
        get: operations["get_meeting"];
        put?: never;
        post?: never;
        /** Soft-delete a meeting */
        delete: operations["delete_meeting"];
        options?: never;
        head?: never;
        /** Update a meeting */
        patch: operations["update_meeting"];
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a meeting's action items */
        get: operations["list_action_items"];
        put?: never;
        /** Add an action item */
        post: operations["create_action_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream the recording (supports Range) */
        get: operations["get_media"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a soft-deleted meeting */
        post: operations["restore_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a meeting's summary */
        get: operations["get_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/summary/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate the summary with AI */
        post: operations["regenerate_summary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a meeting's transcript */
        get: operations["get_transcript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search transcripts */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a transcript segment */
        patch: operations["update_segment"];
        trace?: never;
    };
    "/api/v1/speakers/{speaker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a speaker */
        patch: operations["rename_speaker"];
        trace?: never;
    };
    "/api/v1/transcript-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview pasted transcript text (JSON, nothing is stored) */
        post: operations["create_transcript_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcript-previews/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview an uploaded transcript file (multipart, nothing is stored) */
        post: operations["create_transcript_preview_from_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemCountsRead */
        ActionItemCountsRead: {
            /** Completed */
            completed: number;
            /** Open */
            open: number;
        };
        /** ActionItemCreate */
        ActionItemCreate: {
            /** Assignee Participant Id */
            assignee_participant_id?: number | null;
            /** Due Date */
            due_date?: string | null;
            /** Start Ms */
            start_ms?: number | null;
            /** Text */
            text: string;
        };
        /** ActionItemRead */
        ActionItemRead: {
            assignee: components["schemas"]["AssigneeRead"] | null;
            /** Completed At */
            completed_at: string | null;
            /** Due Date */
            due_date: string | null;
            /** Id */
            id: number;
            /** Meeting Id */
            meeting_id: number;
            source: components["schemas"]["ActionItemSource"];
            /** Start Ms */
            start_ms: number | null;
            status: components["schemas"]["ActionItemStatus"];
            /** Text */
            text: string;
        };
        /**
         * ActionItemSource
         * @enum {string}
         */
        ActionItemSource: "ai" | "manual";
        /**
         * ActionItemStatus
         * @enum {string}
         */
        ActionItemStatus: "open" | "completed";
        /**
         * ActionItemUpdate
         * @description Partial edit; services use model_fields_set so null can clear assignee or due date.
         */
        ActionItemUpdate: {
            /** Assignee Participant Id */
            assignee_participant_id?: number | null;
            /** Due Date */
            due_date?: string | null;
            status?: components["schemas"]["ActionItemStatus"] | null;
            /** Text */
            text?: string | null;
        };
        /** AssigneeRead */
        AssigneeRead: {
            /** Display Name */
            display_name: string;
            /** Id */
            id: number;
        };
        /** Body_create_transcript_preview_from_file */
        Body_create_transcript_preview_from_file: {
            /**
             * File
             * @description VTT, SRT, JSON or plain text.
             */
            file: string;
        };
        /** ChannelCreate */
        ChannelCreate: {
            /** Name */
            name: string;
        };
        /** ChannelRead */
        ChannelRead: {
            /** Id */
            id: number;
            /** Is Private */
            is_private: boolean;
            /** Meeting Count */
            meeting_count: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** ChannelRef */
        ChannelRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** ChannelUpdate */
        ChannelUpdate: {
            /** Name */
            name: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ai Provider */
            ai_provider: string;
            /** Db */
            db: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * MatchRange
         * @description Half-open character offsets into the snippet; the client wraps them, never raw HTML.
         */
        MatchRange: {
            /** End */
            end: number;
            /** Start */
            start: number;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "audio" | "video" | "none";
        /** MeetingCreate */
        MeetingCreate: {
            /** Channel Id */
            channel_id?: number | null;
            /** Description */
            description?: string | null;
            /** Participants */
            participants?: string[];
            /** Segments */
            segments?: components["schemas"]["SegmentIn"][] | null;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "upload" | "paste" | "manual";
            /** Started At */
            started_at?: string | null;
            /** Title */
            title: string;
        };
        /** MeetingDetail */
        MeetingDetail: {
            action_item_counts: components["schemas"]["ActionItemCountsRead"];
            channel: components["schemas"]["ChannelRef"] | null;
            /** Channel Id */
            channel_id: number | null;
            /** Description */
            description: string | null;
            /** Duration Ms */
            duration_ms: number;
            /** Has Media */
            has_media: boolean;
            host: components["schemas"]["UserRef"];
            /** Id */
            id: number;
            /** Keywords */
            keywords: string[];
            /** Language */
            language: string;
            media_type: components["schemas"]["MediaType"];
            /** Meeting Url */
            meeting_url: string | null;
            /** Participant Count */
            participant_count: number;
            /** Participants */
            participants: components["schemas"]["ParticipantRead"][];
            platform: components["schemas"]["Platform"] | null;
            source: components["schemas"]["MeetingSource"];
            /** Speakers */
            speakers: components["schemas"]["SpeakerRead"][];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["MeetingStatus"];
            /** Suggested Tags */
            suggested_tags: string[];
            /**
             * Summary Status
             * @enum {string}
             */
            summary_status: "none" | "ready" | "stale" | "generating";
            /** Tags */
            tags: components["schemas"]["TagRead"][];
            /** Title */
            title: string;
        };
        /**
         * MeetingListItem
         * @description Light row for lists: never carries the transcript.
         */
        MeetingListItem: {
            action_item_counts: components["schemas"]["ActionItemCountsRead"];
            channel: components["schemas"]["ChannelRef"] | null;
            /** Channel Id */
            channel_id: number | null;
            /** Duration Ms */
            duration_ms: number;
            /** Has Media */
            has_media: boolean;
            host: components["schemas"]["UserRef"];
            /** Id */
            id: number;
            /** Keywords */
            keywords: string[];
            /** Language */
            language: string;
            /** Meeting Url */
            meeting_url: string | null;
            /** Overview Preview */
            overview_preview: string | null;
            /** Participant Count */
            participant_count: number;
            /** Participants */
            participants: components["schemas"]["ParticipantRef"][];
            platform: components["schemas"]["Platform"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["MeetingStatus"];
            /** Tags */
            tags: components["schemas"]["TagRead"][];
            /** Title */
            title: string;
        };
        /**
         * MeetingSort
         * @enum {string}
         */
        MeetingSort: "-started_at" | "started_at" | "title" | "-duration_ms";
        /**
         * MeetingSource
         * @enum {string}
         */
        MeetingSource: "seed" | "upload" | "paste" | "manual" | "capture" | "calendar";
        /**
         * MeetingStatus
         * @enum {string}
         */
        MeetingStatus: "scheduled" | "live" | "processing" | "completed";
        /**
         * MeetingUpdate
         * @description Partial update; unset fields are untouched, so null can clear description/channel.
         */
        MeetingUpdate: {
            /** Channel Id */
            channel_id?: number | null;
            /** Description */
            description?: string | null;
            /** Participants */
            participants?: components["schemas"]["ParticipantInput"][] | null;
            /** Started At */
            started_at?: string | null;
            /** Title */
            title?: string | null;
        };
        /** NoteGroupRead */
        NoteGroupRead: {
            /** Bullets */
            bullets: string[];
            /** Title */
            title: string;
        };
        /** OutlineEntryRead */
        OutlineEntryRead: {
            /** Start Ms */
            start_ms: number | null;
            /** Title */
            title: string;
        };
        /** Page[ActionItemRead] */
        Page_ActionItemRead_: {
            /** Has Next */
            readonly has_next: boolean;
            /** Items */
            items: components["schemas"]["ActionItemRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            readonly total_pages: number;
        };
        /** Page[ChannelRead] */
        Page_ChannelRead_: {
            /** Has Next */
            readonly has_next: boolean;
            /** Items */
            items: components["schemas"]["ChannelRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            readonly total_pages: number;
        };
        /** Page[MeetingListItem] */
        Page_MeetingListItem_: {
            /** Has Next */
            readonly has_next: boolean;
            /** Items */
            items: components["schemas"]["MeetingListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            readonly total_pages: number;
        };
        /** Page[SearchHit] */
        Page_SearchHit_: {
            /** Has Next */
            readonly has_next: boolean;
            /** Items */
            items: components["schemas"]["SearchHit"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            readonly total_pages: number;
        };
        /** Page[UserRead] */
        Page_UserRead_: {
            /** Has Next */
            readonly has_next: boolean;
            /** Items */
            items: components["schemas"]["UserRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            readonly total_pages: number;
        };
        /**
         * ParticipantInput
         * @description A participant in an edit; `id` set means "this existing row, possibly renamed".
         */
        ParticipantInput: {
            /** Display Name */
            display_name: string;
            /** Id */
            id?: number | null;
        };
        /** ParticipantRead */
        ParticipantRead: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string | null;
            /** Id */
            id: number;
            role: components["schemas"]["ParticipantRole"];
            /** Talk Ms */
            talk_ms: number;
            /** User Id */
            user_id: number | null;
        };
        /** ParticipantRef */
        ParticipantRef: {
            /** Display Name */
            display_name: string;
            /** Id */
            id: number;
        };
        /**
         * ParticipantRole
         * @enum {string}
         */
        ParticipantRole: "host" | "attendee";
        /**
         * Platform
         * @enum {string}
         */
        Platform: "zoom" | "meet" | "teams" | "other";
        /** SearchHit */
        SearchHit: {
            /** Meeting Id */
            meeting_id: number;
            /** Meeting Title */
            meeting_title: string;
            /** Ranges */
            ranges: components["schemas"]["MatchRange"][];
            /** Segment Id */
            segment_id: number;
            /** Snippet */
            snippet: string;
            /** Speaker */
            speaker: string;
            /** Start Ms */
            start_ms: number;
        };
        /** SegmentIn */
        SegmentIn: {
            /** End Ms */
            end_ms: number;
            /** Speaker */
            speaker: string;
            /** Start Ms */
            start_ms: number;
            /** Text */
            text: string;
        };
        /** SegmentRead */
        SegmentRead: {
            /** End Ms */
            end_ms: number;
            /** Id */
            id: number;
            /** Is Edited */
            is_edited: boolean;
            /** Original Text */
            original_text: string;
            /** Sequence */
            sequence: number;
            /** Speaker Id */
            speaker_id: number;
            /** Start Ms */
            start_ms: number;
            /** Text */
            text: string;
        };
        /** SegmentUpdate */
        SegmentUpdate: {
            /** Text */
            text: string;
        };
        /** SpeakerRead */
        SpeakerRead: {
            /** Color Index */
            color_index: number;
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Participant Id */
            participant_id: number | null;
        };
        /** SpeakerRename */
        SpeakerRename: {
            /** Name */
            name: string;
        };
        /** SummaryRead */
        SummaryRead: {
            /** Generated At */
            generated_at: string | null;
            /** Is Stale */
            is_stale: boolean;
            /** Keywords */
            keywords: string[];
            /** Model */
            model: string | null;
            /** Notes */
            notes: components["schemas"]["NoteGroupRead"][];
            /** Outline */
            outline: components["schemas"]["OutlineEntryRead"][];
            /** Overview */
            overview: string;
            /** Provider */
            provider: string | null;
        };
        /** TagRead */
        TagRead: {
            /** Color Index */
            color_index: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** TranscriptPreview */
        TranscriptPreview: {
            /** Duration Ms */
            duration_ms: number;
            /** Format */
            format: string;
            /** Segment Count */
            segment_count: number;
            /** Segments */
            segments: components["schemas"]["SegmentIn"][];
            /** Speakers */
            speakers: string[];
            /** Timings Estimated */
            timings_estimated: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** TranscriptRead */
        TranscriptRead: {
            /** Segments */
            segments: components["schemas"]["SegmentRead"][];
            /** Speakers */
            speakers: components["schemas"]["SpeakerRead"][];
        };
        /**
         * TranscriptTextIn
         * @description Pasted transcript text, the JSON counterpart of a file upload.
         */
        TranscriptTextIn: {
            /** Filename */
            filename?: string | null;
            /** Text */
            text: string;
        };
        /** UserRead */
        UserRead: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * UserRef
         * @description Minimal identity embedded in every meeting row.
         */
        UserRef: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A dependency is unavailable, e.g. the database is unseeded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_action_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_action_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemRead"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_channels: {
        parameters: {
            query?: {
                page?: number;
                /** @description Clamped to 100. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ChannelRead_"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_channel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"];
                };
            };
            /** @description The request conflicts with current state, e.g. a duplicate name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with current state, e.g. a duplicate name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description A dependency is unavailable, e.g. the database is unseeded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_meetings: {
        parameters: {
            query?: {
                /** @description Prefix `-` means descending. */
                sort?: components["schemas"]["MeetingSort"];
                /** @description Case-insensitive substring of the title, a participant name or the summary overview; or every word in the transcript (last word as a prefix). */
                q?: string | null;
                /** @description Participant name contains. */
                participant?: string | null;
                /** @description Inclusive, UTC day. */
                date_from?: string | null;
                /** @description Inclusive, UTC day. */
                date_to?: string | null;
                /** @description Tag id; repeat for any-of. */
                tag?: number[] | null;
                /** @description Channel id. */
                channel?: number | null;
                scope?: "all" | "hosted" | "shared" | "uploads";
                status?: "completed" | "upcoming";
                page?: number;
                /** @description Clamped to 100. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MeetingListItem_"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A dependency is unavailable, e.g. the database is unseeded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI rate limit exceeded; retry later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The database is unseeded (NOT_SEEDED) or the AI provider failed (AI_UNAVAILABLE). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with current state, e.g. a duplicate name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_action_items: {
        parameters: {
            query?: {
                page?: number;
                /** @description Clamped to 100. */
                page_size?: number;
            };
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ActionItemRead_"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_action_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemRead"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The recording bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": unknown;
                };
            };
            /** @description A byte range of the recording. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": unknown;
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restore_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryRead"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    regenerate_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryRead"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with current state, e.g. a duplicate name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI rate limit exceeded; retry later. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The AI provider failed; `code` is AI_UNAVAILABLE. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_transcript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptRead"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Words to find; matches are ranked by relevance. */
                q: string;
                page?: number;
                /** @description Clamped to 100. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SearchHit_"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_segment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentRead"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_speaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                speaker_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerRead"];
                };
            };
            /** @description The resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The meeting was soft-deleted; restore it to use it again. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_transcript_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscriptTextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptPreview"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_transcript_preview_from_file: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_transcript_preview_from_file"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptPreview"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: {
                page?: number;
                /** @description Clamped to 100. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserRead_"];
                };
            };
            /** @description Invalid input; `details.errors[].loc` is the field path. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
