import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import { AppProviders } from "@/components/ui";
import { PlayerProvider, VirtualClockEngine } from "@/features/player";
import type { Summary } from "@/lib/api";

import { fetchSummary } from "../api";
import { SummaryPanel } from "./SummaryPanel";

vi.mock("../api", () => ({ fetchSummary: vi.fn(), regenerateSummary: vi.fn() }));

const full: Summary = {
  overview: "We planned the rollout.",
  keywords: ["rollout"],
  outline: [{ title: "Plan", start_ms: 0 }],
  notes: [{ title: "Plan", bullets: ["Ship it"] }],
  provider: "mock",
  model: null,
  generated_at: new Date().toISOString(),
  is_stale: true,
};

function renderPanel() {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(
    <QueryClientProvider client={client}>
      <AppProviders>
        <PlayerProvider
          durationMs={60_000}
          createEngine={({ durationMs }) => new VirtualClockEngine({ durationMs })}
        >
          <SummaryPanel meetingId={1} durationMs={60_000} actionItemsSlot={<p>ITEMS</p>} />
        </PlayerProvider>
      </AppProviders>
    </QueryClientProvider>,
  );
}

describe("SummaryPanel", () => {
  it("renders the five sections in canonical order with attribution and stale badge", async () => {
    vi.mocked(fetchSummary).mockResolvedValue(full);
    renderPanel();
    await screen.findByText("We planned the rollout.");
    expect(screen.getAllByRole("heading", { level: 3 }).map((h) => h.textContent)).toEqual([
      "Keywords",
      "Meeting Overview",
      "Meeting Outline",
      "Bullet-Point Notes",
      "Action Items",
    ]);
    expect(screen.getByText("Generated by mock · just now")).toBeTruthy();
    expect(screen.getByText("Outdated")).toBeTruthy();
    expect(screen.getByRole("button", { name: "Jump to Plan at 00:00 – 01:00" })).toBeTruthy();
    expect(screen.getByText("ITEMS")).toBeTruthy();
  });

  it("shows the empty state but still the action items for a never-summarised meeting", async () => {
    vi.mocked(fetchSummary).mockResolvedValue({
      ...full,
      overview: "",
      keywords: [],
      outline: [],
      notes: [],
      provider: null,
      generated_at: null,
      is_stale: false,
    });
    renderPanel();
    expect(await screen.findByText("No summary yet")).toBeTruthy();
    expect(screen.getByText("ITEMS")).toBeTruthy();
  });
});
