"use client";

import { Check, ChevronDown, Copy, MoreHorizontal, Plus, RefreshCw, Sparkles } from "lucide-react";
import { useState } from "react";

import {
  Badge,
  Button,
  ConfirmDialog,
  IconButton,
  Menu,
  SoonBadge,
  Spinner,
  Tooltip,
  toast,
} from "@/components/ui";

import { formatRelative } from "@/lib/utils/relative-time";
import { NOTE_TEMPLATES, type TemplateId } from "../lib/templates";

export type SummaryHeaderProps = {
  templateId: TemplateId;
  onTemplateChange: (id: string) => void;
  onCopy: () => void;
  canCopy: boolean;
  provider: string | null;
  model: string | null;
  generatedAt: string | null;
  isStale: boolean;
  onRegenerate: () => void;
  isRegenerating: boolean;
};

export function SummaryHeader({
  templateId,
  onTemplateChange,
  onCopy,
  canCopy,
  provider,
  model,
  generatedAt,
  isStale,
  onRegenerate,
  isRegenerating,
}: SummaryHeaderProps) {
  const [confirmOpen, setConfirmOpen] = useState(false);
  const currentLabel = NOTE_TEMPLATES.find((t) => t.id === templateId)?.label ?? "General";

  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-wrap items-center gap-2">
        <Menu
          align="start"
          items={NOTE_TEMPLATES.map((t) => ({
            label: `${t.label} Notes`,
            onSelect: () => onTemplateChange(t.id),
            trailing:
              t.id === templateId ? (
                <Check className="text-accent" strokeWidth={1.75} />
              ) : undefined,
          }))}
          trigger={
            <Button
              size="sm"
              variant="ghost"
              aria-label={`Note template: ${currentLabel} Notes`}
              leadingIcon={<Sparkles strokeWidth={1.75} />}
              trailingIcon={<ChevronDown strokeWidth={1.75} />}
              className="px-2 text-accent hover:text-accent"
            >
              {currentLabel} Notes
            </Button>
          }
        />
        <IconButton
          label="Copy summary as Markdown"
          size="sm"
          icon={<Copy strokeWidth={1.75} />}
          onClick={onCopy}
          disabled={!canCopy}
        />
        <Button
          size="sm"
          variant="secondary"
          leadingIcon={<Plus strokeWidth={1.75} />}
          trailingIcon={<SoonBadge />}
          onClick={() => toast.info("AI Apps are coming soon")}
        >
          AI Apps
        </Button>
        <div className="ml-auto flex items-center gap-1">
          {isRegenerating && <Spinner label="Regenerating summary" />}
          <Menu
            trigger={
              <IconButton
                label="Summary options"
                size="sm"
                tooltip={false}
                icon={<MoreHorizontal strokeWidth={1.75} />}
              />
            }
            items={[
              {
                label: isRegenerating ? "Regenerating…" : "Regenerate summary",
                icon: <RefreshCw strokeWidth={1.75} />,
                disabled: isRegenerating,
                onSelect: () => setConfirmOpen(true),
              },
            ]}
          />
        </div>
      </div>

      {(provider || isStale) && (
        <div className="flex flex-wrap items-center gap-2 text-caption text-muted">
          {provider && (
            <span title={model ?? undefined}>
              Generated by {provider}
              {generatedAt && ` · ${formatRelative(generatedAt)}`}
            </span>
          )}
          {isStale && (
            <Tooltip content="The transcript changed after this summary was generated. Regenerate to update it.">
              <Badge tone="warning" tabIndex={0}>
                Outdated
              </Badge>
            </Tooltip>
          )}
          {isStale && (
            <Button
              size="sm"
              variant="ghost"
              className="h-6 px-2 text-caption"
              leadingIcon={<RefreshCw strokeWidth={1.75} />}
              loading={isRegenerating}
              onClick={() => setConfirmOpen(true)}
            >
              Regenerate
            </Button>
          )}
        </div>
      )}

      <ConfirmDialog
        open={confirmOpen}
        onOpenChange={setConfirmOpen}
        title="Regenerate summary?"
        description="The current overview, outline and notes will be replaced with a fresh AI summary."
        confirmLabel="Regenerate"
        onConfirm={() => {
          setConfirmOpen(false);
          onRegenerate();
        }}
      />
    </div>
  );
}
